mkvtoolnixPath: C:\Program Files\MKVToolNix
# Only edit this value if you know what you are doing, otherwise it may impact your performance negatively
threadCount: 2
config:
  1:
    audio:
      - jpn
    subtitle:
      - ger
      - eng
  2:
    audio:
      - ger
      - eng
    subtitle:
      - OFF