mkvtoolnix: C:\Program Files\MKVToolNix

config:
  1:
    audio: ger
    subtitle: OFF
  2:
    audio: eng
    subtitle: ger

# Recommendations for data stored on HDDs, increase when using SSDs
#threads: 2
#forcedKeywords: ["forced", "signs"]
#exclude-directories:
#  - "D:/Path/To/File.mkv"
#  - "D:/Path/To/Directory"
#include-pattern: "regex"

